import os

from krrood.ormatic.custom_types import PolymorphicEnumType
from ..dataset.ormatic_interface import SceneObjectDAO

# %% the generated file


def test_generation_process():
    """
    Test that the SQLAlchemy interface was generated correctly.

    This krrood_test verifies that the ormatic_interface.py file was generated by the
    pytest_configure hook and contains the expected content. The actual generation
    happens in conftest.py before tests run.
    """
    # Verify that the file was created
    file_path = os.path.join(
        os.path.dirname(__file__), "..", "dataset", "ormatic_interface.py"
    )
    assert os.path.exists(file_path)

    # Verify that the file has the expected header
    with open(file_path, "r") as f:
        content = f.read()
        assert "# Generated by ORMatic" in content
        assert "import krrood.ormatic.base" in content
        assert "Base = krrood.ormatic.base.Base" in content

    # Verify we can import from the generated file
    from ..dataset import ormatic_interface

    assert hasattr(ormatic_interface, "Base")

    # Verify that expected DAO classes exist
    assert hasattr(ormatic_interface, "KRROODTransformationMappedDAO")
    assert hasattr(ormatic_interface, "KRROODPositionDAO")
    assert hasattr(ormatic_interface, "AtomDAO")


# %% default type mappings


def test_an_enum_field_maps_to_a_polymorphic_enum_column_by_default():
    """
    Enums map polymorphically without the generating side registering anything, so an
    interface that asks for no type mapping of its own still stores any enum member.
    """
    assert isinstance(
        SceneObjectDAO.__table__.columns["type"].type, PolymorphicEnumType
    )
